### ISSUE TITLE
check_aggregate doesn't work with sensu-server 1.x.x

### ISSUE THREAD

**Issue by nishiki** [sensu-plugins/sensu-plugins-sensu#33]
Hello,

I have upgrade sensu-server 0.25 to 1.0.2, and since the check_aggregate doesn't work.

```
./check-aggregate.rb -A 60 -c "elasticsearch-cluster-log" -W 1 -a http://localhost:4567
Check failed to run: bad URI(is not URI?): http://localhost:4567/aggregates/elasticsearch-cluster-log/[:results, {:ok=>5, :warning=>0, :critical=>0, :unknown=>0, :total=>5, :stale=>0}]?, ["/opt/sensu/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'", "/opt/sensu/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'", "/opt/sensu/embedded/lib/ruby/2.4.0/uri/common.rb:231:in `parse'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:276:in `parse_url'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:280:in `parse_url_with_auth'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:175:in `execute'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-1.1.0/bin/check-aggregate.rb:134:in `api_request'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-1.1.0/bin/check-aggregate.rb:201:in `aggregate_results'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-1.1.0/bin/check-aggregate.rb:181:in `acquire_aggregate'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-1.1.0/bin/check-aggregate.rb:273:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```
I have a fix for this problem.

Regards,

**Comment by majormoses** [comment]
closed via #34
