### ISSUE TITLE
check-stale-results.rb errors out when parsing results

### ISSUE THREAD

**Issue by asachs01** [sensu-plugins/sensu-plugins-sensu#41]
We've recently encountered an error when running a check using `check-stale-results.rb`. It appears as the following:

```
{"timestamp":"2017-09-21T11:23:49.169000-0500","level":"info","message":"handler extension output","extension":{"type":"extension","name":"debug"},"event":{"id":"1475d37d-eaa2-483c-8629-a72f212e162a"},"output":"{\"client\":{\"name\":\"khalkotauroi.local\",\"address\":\"192.168.156.237\",\"environment\":\"production\",\"subscriptions\":[\"production\",\"client:khalkotauroi.local\"],\"version\":\"1.0.2\",\"timestamp\":1506011026},\"check\":{\"command\":\"/opt/sensu/embedded/bin/check-stale-results.rb -s 3d -c 5 -w 1\",\"subscribers\":[\"production\"],\"interval\":10,\"name\":\"results\",\"issued\":1506011028,\"executed\":1506011028,\"duration\":0.159,\"output\":\"Check failed to run: wrong number of arguments (given 2, expected 3), [\\\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:63:in `api_request'\\\", \\\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:78:in `results'\\\", \\\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:51:in `initialize'\\\", \\\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'\\\", \\\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'\\\"]\\n\",\"status\":2,\"type\":\"standard\",\"history\":[\"2\",\"2\",\"2\",\"2\",\"2\"],\"total_state_change\":0},\"occurrences\":5,\"occurrences_watermark\":5,\"action\":\"create\",\"timestamp\":1506011029,\"id\":\"1475d37d-eaa2-483c-8629-a72f212e162a\",\"last_state_change\":1506010619,\"last_ok\":1506010619,\"silenced\":false,\"silenced_by\":[]}","status":0}
```

Something that's perhaps a bit more readable:

```
$/opt/sensu/embedded/bin/ruby check-stale-results.rb -c 5 -w 1 -s 
Check failed to run: wrong number of arguments (given 2, expected 3), ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:63:in 
`api_request'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:78:in `results'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/ge
ms/sensu-plugins-sensu-2.2.0/bin/check-stale-results.rb:51:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new
'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```
I'd include some expected output here, but since we're not able to run the check successfully, we don't have any to provide.

**Comment by majormoses** [comment]
Thanks for reporting this, there were some recent bug fixes that we merged and released. I am not sure if this problem is the same. Could you try updating to the most recent version of this gem and retest?

**Comment by robertlabrie** [comment]
So I just encountered something similar with sensu-plugin-2.3.0 (downgrading to 2.0.1 resolved the issue for me). Same `CheckPddReplication UNKNOWN: ArgumentError - wrong number of arguments (given 2, expected 0)` Relevant part of our class is:

```
class CheckPddReplication < Sensu::Plugin::Check::CLI
  option :user,
         description: 'User to authenticate against PDD with',
         short: '-u',
         long: '--user USER',
         required: false,
         default: 'pdd'

  option :pass,
         description: 'Pass to authenticate against PDD with',
         short: '-p',
         long: '--pass PASS',
         required: false,
         default: 'password'

...
```

**Comment by robertlabrie** [comment]
So I'm encountering the same error. TL;DR it's working on a machine with a slightly older sensu install, but not on one with the latest.
```
/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-pdd-replication.rb --user notreallytheuser --pass notreallythepassword
CheckPddReplication UNKNOWN: ArgumentError - wrong number of arguments (given 2, expected 0)
```

The relevant part of my check:
```
#!/usr/bin/env ruby
#
# Check PDD Replication
#

require 'sensu-plugin/check/cli'
require 'json'
require 'rest-client'
require 'socket'

# Checks for PDD replication issues
class CheckPddReplication < Sensu::Plugin::Check::CLI
  option :user,
         description: 'User to authenticate against PDD with',
         short: '-u',
         long: '--user USER',
         required: false,
         default: 'pdd'

  option :pass,
         description: 'Pass to authenticate against PDD with',
         short: '-p',
         long: '--pass PASS',
         required: false,
         default: 'password'
```

On this machine it doesn't work
```
/opt/sensu/embedded/bin/gem list | grep sensu
sensu (0.29.0)
sensu-extension (1.5.1)
sensu-extensions (1.9.0)
sensu-extensions-check-dependencies (1.0.1)
sensu-extensions-debug (1.0.0)
sensu-extensions-json (1.0.0)
sensu-extensions-occurrences (1.2.0)
sensu-extensions-only-check-output (1.0.0)
sensu-extensions-ruby-hash (1.0.0)
sensu-json (2.1.0)
sensu-logger (1.2.1)
sensu-plugin (2.3.0, 2.0.1, 1.4.5)
sensu-plugins-docker (1.5.0)
sensu-plugins-elasticsearch (1.7.1)
sensu-plugins-kubernetes (3.0.0)
sensu-plugins-network-checks (2.0.1)
sensu-plugins-pagerduty (3.0.0)
sensu-plugins-process-checks (2.5.0)
sensu-plugins-sensu (2.3.1)
sensu-plugins-ssl (1.5.0)
sensu-plugins-zookeeper (1.3.0)
sensu-redis (2.1.1)
sensu-settings (10.0.0)
sensu-spawn (2.2.1)
sensu-transport (7.0.2)
```

but on this one it DOES work:

```
/opt/sensu/embedded/bin/gem list | grep sensu
sensu (0.29.0)
sensu-extension (1.5.1)
sensu-extensions (1.9.0)
sensu-extensions-check-dependencies (1.0.1)
sensu-extensions-debug (1.0.0)
sensu-extensions-json (1.0.0)
sensu-extensions-occurrences (1.2.0)
sensu-extensions-only-check-output (1.0.0)
sensu-extensions-ruby-hash (1.0.0)
sensu-json (2.1.0)
sensu-logger (1.2.1)
sensu-plugin (2.0.1, 1.4.5, 1.2.0)
sensu-plugins-docker (0.0.4)
sensu-plugins-elasticsearch (1.3.1)
sensu-plugins-kubernetes (1.0.0)
sensu-plugins-network-checks (1.0.0)
sensu-plugins-process-checks (0.0.6)
sensu-plugins-sensu (1.0.0)
sensu-plugins-ssl (1.3.1)
sensu-plugins-zookeeper (0.1.0)
sensu-redis (2.1.1)
sensu-settings (10.0.0)
sensu-spawn (2.2.1)
sensu-transport (7.0.2)
```

**Comment by majormoses** [comment]
Did you delete some issue comments? My email shows that you did some more triage but I am not seeing it on github. Should I repost it or investigate what I see in the email?

**Comment by robertlabrie** [comment]
@majormoses yes, I did, and I should have mentioned it, sorry. My problem turned out to not be related to Sensu at all, and I didn't want it cluttering up the thread. My apologies.

**Comment by majormoses** [comment]
No worries I will ignore them. Can you please try testing with the latest released version before trying to triage a possibly fixed issue?
